service: soca-kickstart
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  githubToken: ${ssm:github.token}
  cfnRole: arn:aws:iam::${self:custom.config.${self:provider.stage}.account_id}:role/CloudFormationExecutionRole

custom:
  config:
    dev:
      account_id: ${opt:accountId, '921358061875'}
      branch: dev
      code_owner: ${opt:codeOwner, 'imsergiocano'}
      json_path: '$.ref'
      match_equals: ref/heads/{Branch}


resources:
  - ${file(api.yml)}