---

Resources:
  CodeBuildExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CodeBuildExecutionPolicy
      Description: Policy created
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - codebuild:StartBuild
          - codebuild:StopBuild
          - codebuild:StartBuildBatch
          - codebuild:StopBuildBatch
          - codebuild:RetryBuild
          - codebuild:RetryBuildBatch
          - codebuild:BatchGet*
          - codebuild:GetResourcePolicy
          - codebuild:DescribeTestCases
          - codebuild:DescribeCodeCoverages
          - codebuild:List*
          - logs:*
          - s3:*
          - ssm:GetParameter*
          Resource: '*'
        - Effect: Allow
          Action:
          - iam:PassRole
          Resource:
          - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/CodeBuildExecutionRole
  
  CodePipeLineExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CodePipeLineExecutionPolicy
      Description: Policy created
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - codepipeline:*
          - s3:*
          - codebuild:StartBuild
          - codebuild:BatchGet*
          Resource: '*'
        - Effect: Allow
          Action:
          - iam:PassRole
          Resource:
          - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/CodePipeLineExecutionRole          
  