service: soca-kickstart-pipeline
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  githubToken: ${ssm:github.token}

custom:
  config:
    dev:
      account_id: ${opt:accountId, '145794000460'}
      branch: dev
      code_owner: ${opt:codeOwner, 'imsergiocano'}
      json_path: '$.ref'
      match_equals: ref/heads/{Branch}
resources:
  - ${file(policies.yml)}
  - ${file(roles.yml)}
  - ${file(pipeline.yml)}